/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "خريطة أساس",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "خريطة الأساس",
        sendsTheBasemapChosenInEither: "يرسل خريطة القاعدة التي تم اختيارها في أي من معرض ألعاب القاعدة إلى التطبيق التالي The destination app needs a Map Switcher connected to its map to apply it.",
        noMapSelectedTheFirstMap: "No map selected: the first Map widget in the app is used. اختيار واحد هنا إذا كان التطبيق لديه أكثر من خريطة واحدة.",
        sites: "المقاعد",
        siteIndex: "Site {index}",
        moveUp: "انتقال إلى أعلى",
        moveSiteIndexUp: "موقع النقل {index} استيقظ",
        moveDown: "انتقال إلى أسفل",
        moveSiteIndexDown: "موقع النقل {index} للأسفل",
        label: "التسمية",
        siteName: "اسم الموقع",
        url: "URL",
        remove: "إزالة",
        addSite: "مضبوطة"
      })
    }
  }
})
