/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Базова карта",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Пренасяне на базова карта към следващата карта",
        sendsTheBasemapChosenInEither: "Изпращане на основната карта, избрана в някоя от базовите карти галерия към следващото приложение. Приложението за местоназначение се нуждае от Map Switcher, свързан към картата му, за да го прилага.",
        noMapSelectedTheFirstMap: "Не е избрана карта: се използва първата карта джаджа в приложението. Изберете един тук, ако приложението има повече от една карта.",
        sites: "Обекти",
        siteIndex: "Място {index}",
        moveUp: "Нагоре",
        moveSiteIndexUp: "Преместване на мястото {index} Нагоре",
        moveDown: "Надолу",
        moveSiteIndexDown: "Преместване на мястото {index} Долу",
        label: "Надпис",
        siteName: "Име на сайта",
        url: "URL адрес",
        remove: "Премахване",
        addSite: "Добавяне на сайта"
      })
    }
  }
})
