/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Podkladová mapa",
        mapWidget: "Name",
        carryBasemapToNextMap: "Přenést basemap na další mapu",
        sendsTheBasemapChosenInEither: "Odesílá basemap vybraný v každé z nich galerie na další aplikaci. Cílová aplikace potřebuje přepínač mapy připojený k její mapě, aby ji mohl použít.",
        noMapSelectedTheFirstMap: "Není zvolena žádná mapa: je použit první widget mapy v aplikaci. Vyberte jednu zde, pokud aplikace má více než jednu mapu.",
        sites: "Stránky",
        siteIndex: "Místo {index}",
        moveUp: "Přesunout nahoru",
        moveSiteIndexUp: "Přesun {index} Nahoru",
        moveDown: "Přesunout dolů",
        moveSiteIndexDown: "Přesun {index} dolů",
        label: "Popisek",
        siteName: "Název lokality",
        url: "Adresa URL",
        remove: "Odebrat",
        addSite: "Přidat místo"
      })
    }
  }
})
