/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Υπόβαθρο",
        mapWidget: "Γραφικό συστατικό χάρτη",
        carryBasemapToNextMap: "Μεταφορά χάρτη βάσης στον επόμενο χάρτη",
        sendsTheBasemapChosenInEither: "Στέλνει τον χάρτη βάσης που επιλέγεται σε οποιαδήποτε γκαλερί basemap στην επόμενη εφαρμογή. Η εφαρμογή προορισμού χρειάζεται ένα Map Switcher συνδεδεμένο στο χάρτη του για να το εφαρμόσει.",
        noMapSelectedTheFirstMap: "Δεν επιλέχθηκε χάρτης: χρησιμοποιείται το πρώτο γραφικό συστατικό χάρτη στην εφαρμογή. Επιλέξτε ένα εδώ αν η εφαρμογή έχει περισσότερους από έναν χάρτες.",
        sites: "Τόποι",
        siteIndex: "Ιστοσελίδα {index}",
        moveUp: "Μετακίνηση προς τα επάνω",
        moveSiteIndexUp: "Μετακίνηση τοποθεσίας {index} Πάνω",
        moveDown: "Μετακίνηση προς τα κάτω",
        moveSiteIndexDown: "Μετακίνηση τοποθεσίας {index} Κάτω",
        label: "Ετικέτα",
        siteName: "Όνομα τοποθεσίας",
        url: "Διεύθυνση URL",
        remove: "Κατάργηση",
        addSite: "Προσθήκη τοποθεσίας"
      })
    }
  }
})
