/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Mapa base",
        mapWidget: "Mapa widget",
        carryBasemapToNextMap: "Carry basemap al siguiente mapa",
        sendsTheBasemapChosenInEither: "Envia el mapa base elegido en la galería basemap a la siguiente aplicación. La aplicación de destino necesita un conmutador de mapa conectado a su mapa para aplicarlo.",
        noMapSelectedTheFirstMap: "No se ha seleccionado ningún mapa: se utiliza el primer widget de mapa en la aplicación. Seleccione uno aquí si la aplicación tiene más de un mapa.",
        sites: "Sitios",
        siteIndex: "Sitio {index}",
        moveUp: "Mover hacia arriba",
        moveSiteIndexUp: "Mover sitio {index} arriba",
        moveDown: "Mover hacia abajo",
        moveSiteIndexDown: "Mover sitio {index} abajo",
        label: "Etiqueta",
        siteName: "Nombre del sitio",
        url: "URL",
        remove: "Eliminar",
        addSite: "Agregar sitio"
      })
    }
  }
})
