/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Aluskaart",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Aluskaardi kandmine järgmisele kaardile",
        sendsTheBasemapChosenInEither: "Saadab mõlemas aluskaardi galeriis valitud aluskaardi järgmisele rakendusele. Sihtkoha rakendus vajab selle rakendamiseks kaardilülitit, mis on ühendatud selle kaardiga.",
        noMapSelectedTheFirstMap: "Kaarti pole valitud: kasutatakse rakenduse esimest kaardividinat. Valige üks siin, kui rakendusel on rohkem kui üks kaart.",
        sites: "Saidid",
        siteIndex: "Site {index}",
        moveUp: "Liiguta ülespoole",
        moveSiteIndexUp: "Liikumiskoht {index} üles",
        moveDown: "Liiguta allapoole",
        moveSiteIndexDown: "Liikumiskoht {index} alla",
        label: "Märgis",
        siteName: "Saidi nimi",
        url: "URL",
        remove: "Eemalda",
        addSite: "Lisa veebileht"
      })
    }
  }
})
