/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Taustakartta",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Kantaa pohjakartta seuraavaan karttaan",
        sendsTheBasemapChosenInEither: "Lähettää joko basemap galleriassa valitun pohjakartta seuraavan sovelluksen. Kohdesovellus tarvitsee karttaan liitetyn karttakytkimen.",
        noMapSelectedTheFirstMap: "Karttaa ei ole valittu: käytetään sovelluksen ensimmäistä kartta-elementtiä. Valitse yksi tästä, jos sovelluksessa on useampi kuin yksi kartta.",
        sites: "Sivustot",
        siteIndex: "Alue {index}",
        moveUp: "Siirrä ylös",
        moveSiteIndexUp: "Siirrä sivusto {index} ylös",
        moveDown: "Siirry alas",
        moveSiteIndexDown: "Siirrä sivusto {index} alas",
        label: "Tunnusteksti",
        siteName: "Kohteen nimi",
        url: "URL-osoite",
        remove: "Poista",
        addSite: "Lisää sivu"
      })
    }
  }
})
