/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Fond de carte",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Porter la carte de base à la carte suivante",
        sendsTheBasemapChosenInEither: "Envoie la carte de base choisie dans chaque galerie de carte de base à l'application suivante. L'application de destination a besoin d'un commutateur de carte connecté à sa carte pour l'appliquer.",
        noMapSelectedTheFirstMap: "Aucune carte sélectionnée : le premier widget Map de l'application est utilisé. Sélectionnez-en un ici si l'application a plus d'une carte.",
        sites: "Sites",
        siteIndex: "Site {index}",
        moveUp: "Monter",
        moveSiteIndexUp: "Déplacer le site {index} en haut",
        moveDown: "Descendre",
        moveSiteIndexDown: "Déplacer le site {index} baisse",
        label: "Étiquette",
        siteName: "Nom du site",
        url: "URL",
        remove: "Supprimer",
        addSite: "Ajouter un site"
      })
    }
  }
})
