/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "מפת בסיס",
        mapWidget: "מפה widget",
        carryBasemapToNextMap: "ערכת בסיס למפה הבאה",
        sendsTheBasemapChosenInEither: "שולח את מפת הבסיס שנבחרה בגלריית מפת בסיס לאפליקציית הבאה. אפליקציית היעד זקוקה ל- Map Switcher המחובר למפה כדי ליישם אותה.",
        noMapSelectedTheFirstMap: "אין מפה שנבחרה: הראשון מפה widget ביישום משמש. בחרו כאן אם לאפליקציית יש יותר ממפה אחת.",
        sites: "אתרים",
        siteIndex: "אתר Site {index}",
        moveUp: "הזז למעלה",
        moveSiteIndexUp: "העברת אתר {index} למעלה",
        moveDown: "הזז למטה",
        moveSiteIndexDown: "העברת אתר {index} למטה למטה",
        label: "תווית",
        siteName: "שם אתר",
        url: "כתובת URL",
        remove: "הסר",
        addSite: "הוסף אתר"
      })
    }
  }
})
