/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Alaptérkép",
        mapWidget: "Térképek",
        carryBasemapToNextMap: "Basemap átvitele a következő térképre",
        sendsTheBasemapChosenInEither: "A bazemapot bármelyik basemap galériában a következő alkalmazásra küldi. A célalkalmazáshoz egy térképváltóra van szükség, amely a térképéhez csatlakozik.",
        noMapSelectedTheFirstMap: "Nincs kijelölve térkép: az alkalmazásban található első térkép widget. Válasszon ki egyet, ha az alkalmazásnak egynél több térképe van.",
        sites: "Oldalak",
        siteIndex: "Helyszín {index}",
        moveUp: "Feljebb",
        moveSiteIndexUp: "Mozgatás {index} Fel",
        moveDown: "Lejjebb",
        moveSiteIndexDown: "Mozgatás {index} lefelé",
        label: "Felirat",
        siteName: "Webhely neve",
        url: "URL",
        remove: "Eltávolítás",
        addSite: "Helyszín hozzáadása"
      })
    }
  }
})
