/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Peta Dasar",
        mapWidget: "Widget peta",
        carryBasemapToNextMap: "Bawa peta dasar ke peta berikutnya",
        sendsTheBasemapChosenInEither: "Mengirim peta dasar yang dipilih dalam galeri peta dasar ke aplikasi berikutnya. Aplikasi tujuan memerlukan Pengalih Peta yang terhubung ke peta untuk menerapkannya.",
        noMapSelectedTheFirstMap: "Tak ada peta yang dipilih: Widget Peta pertama di aplikasi dipakai. Pilih satu di sini jika aplikasi memiliki lebih dari satu peta.",
        sites: "Situs",
        siteIndex: "Situs {index}",
        moveUp: "Geser ke atas",
        moveSiteIndexUp: "Pindah situs {index} naik",
        moveDown: "Geser ke bawah",
        moveSiteIndexDown: "Pindah situs {index} turun",
        label: "Label",
        siteName: "Nama tempat",
        url: "URL",
        remove: "Hapus",
        addSite: "Tambah Situs"
      })
    }
  }
})
