/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Mappa di base",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Carry basemap per la prossima mappa",
        sendsTheBasemapChosenInEither: "Invia la mappa di base scelta nella galleria di basemap alla prossima app. L'app di destinazione ha bisogno di un Switcher Map collegato alla sua mappa per applicarlo.",
        noMapSelectedTheFirstMap: "Nessuna mappa selezionata: viene utilizzato il primo widget della mappa nell'app. Selezionare uno qui se l'applicazione ha più di una mappa.",
        sites: "Siti",
        siteIndex: "Sito web {index}",
        moveUp: "Sposta su",
        moveSiteIndexUp: "Spostare il sito {index} su",
        moveDown: "Sposta giù",
        moveSiteIndexDown: "Spostare il sito {index} giù",
        label: "Etichetta",
        siteName: "Nome del sito",
        url: "URL",
        remove: "Rimuovi",
        addSite: "Aggiungi il sito"
      })
    }
  }
})
