/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "ベースマップ",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "次のマップへ",
        sendsTheBasemapChosenInEither: "ベースマップギャラリーで選択したベースマップを次のアプリに送信します。 宛先アプリは、マップに接続されたマップに接続されたマップが必要です。",
        noMapSelectedTheFirstMap: "選択したマップなし:アプリの最初のマップウィジェットが使用されます。 アプリが複数のマップを持っている場合は、こちらを選択します。",
        sites: "サイトマップ",
        siteIndex: "サイトマップ {index}",
        moveUp: "上に移動",
        moveSiteIndexUp: "サイトマップ {index} ニュース",
        moveDown: "下に移動",
        moveSiteIndexDown: "サイトマップ {index} ダウンダウン",
        label: "ラベル",
        siteName: "サイトマップ",
        url: "URL",
        remove: "削除",
        addSite: "サイトの追加"
      })
    }
  }
})
