/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "베이스맵",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Carry basemap to next map",
        sendsTheBasemapChosenInEither: "Sends the basemap chosen in either basemap gallery to the next app. The destination app needs a Map Switcher connected to its map to apply it.",
        noMapSelectedTheFirstMap: "No map selected: the first Map widget in the app is used. Select one here if the app has more than one map.",
        sites: "Sites",
        siteIndex: "Site {index}",
        moveUp: "위로 이동",
        moveSiteIndexUp: "Move site {index} up",
        moveDown: "아래로 이동",
        moveSiteIndexDown: "Move site {index} down",
        label: "레이블",
        siteName: "Site name",
        url: "URL",
        remove: "제거",
        addSite: "Add Site"
      })
    }
  }
})
