/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Pagrindo žemėlapis",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Perkelti basemap į kitą žemėlapį",
        sendsTheBasemapChosenInEither: "Siunčia basemap pasirinktą arba basemap galerija į kitą programą. Paskirties programėlei reikia Žemėlapio perjungiklio, prijungto prie žemėlapio.",
        noMapSelectedTheFirstMap: "Nepasirinktas žemėlapis: naudojamas pirmasis programos Žemėlapio valdiklis. Pasirinkite vieną čia, jei programa turi daugiau nei vieną žemėlapį.",
        sites: "Teritorijos",
        siteIndex: "Vieta {index}",
        moveUp: "Pakelti aukštyn",
        moveSiteIndexUp: "Perkelti vietą {index} aukštyn",
        moveDown: "Nuleisti žemyn",
        moveSiteIndexDown: "Perkelti vietą {index} žemyn",
        label: "Žymė",
        siteName: "Teritorijos pavadinimas",
        url: "URL",
        remove: "Panaikinti",
        addSite: "Pridėti svetainę"
      })
    }
  }
})
