/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Pamatkarte",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Pārvietot bāzes karti uz nākamo karti",
        sendsTheBasemapChosenInEither: "Nosūta izvēlētās bāzes kartes vai nu bāzes kartes galerijā uz nākamo programmu. Lai to piemērotu, mērķa lietotnei ir nepieciešams ar karti savienots karšu pārslēdzējs.",
        noMapSelectedTheFirstMap: "Nav izvēlēta karte: tiek izmantota pirmā lietotnes karte. Šeit izvēlieties vienu, ja programmai ir vairāk nekā viena karte.",
        sites: "Vietnes",
        siteIndex: "Vieta {index}",
        moveUp: "Pārvietot uz augšu",
        moveSiteIndexUp: "Pārvietot vietu {index} līdz",
        moveDown: "Pārvietot uz leju",
        moveSiteIndexDown: "Pārvietot vietu {index} lejup",
        label: "Nosaukums",
        siteName: "Vietas nosaukums",
        url: "Vietrādis (URL)",
        remove: "Noņemt",
        addSite: "Pievienot vietni"
      })
    }
  }
})
