/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Basiskaart",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Basiskaart naar volgende kaart dragen",
        sendsTheBasemapChosenInEither: "Stuurt de basismap die in beide basismapgalerijen is gekozen naar de volgende app. De bestemmingsapp heeft een kaartwisselaar nodig die is aangesloten op de kaart om deze toe te passen.",
        noMapSelectedTheFirstMap: "Geen kaart geselecteerd: de eerste kaartwidget in de app wordt gebruikt. Selecteer hier één als de app meer dan één kaart heeft.",
        sites: "Sites",
        siteIndex: "Site {index}",
        moveUp: "Naar boven verplaatsen",
        moveSiteIndexUp: "Plaats verplaatsen {index} omhoog",
        moveDown: "Naar beneden verplaatsen",
        moveSiteIndexDown: "Plaats verplaatsen {index} omlaag",
        label: "Label",
        siteName: "Sitenaam",
        url: "URL",
        remove: "Verwijderen",
        addSite: "Site toevoegen"
      })
    }
  }
})
