/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Bakgrunnskart",
        mapWidget: "Kart widget",
        carryBasemapToNextMap: "Bær basekart til neste kart",
        sendsTheBasemapChosenInEither: "Sender basiskartet valgt i enten basiskartgalleri til neste app. Destinasjon app trenger en Map Switcher koblet til sitt kart for å bruke det.",
        noMapSelectedTheFirstMap: "Ingen kart valgt: den første kart widgeten i appen brukes. Velg et her hvis appen har mer enn ett kart.",
        sites: "Nettsteder",
        siteIndex: "Nettsted {index}",
        moveUp: "Flytt opp",
        moveSiteIndexUp: "Flytteområde {index} opp",
        moveDown: "Flytt ned",
        moveSiteIndexDown: "Flytteområde {index} ned",
        label: "Etikett",
        siteName: "Nettstedsnavn",
        url: "URL",
        remove: "Fjern",
        addSite: "Legg til nettsted"
      })
    }
  }
})
