/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Mapa bazowa",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Przenieś Basemap do następnej mapy",
        sendsTheBasemapChosenInEither: "Wysyła do następnej aplikacji mapę bazową wybraną w każdej galerii. Aplikacja docelowa potrzebuje Map Switcher podłączonego do mapy, aby ją zastosować.",
        noMapSelectedTheFirstMap: "Nie wybrano mapy: używany jest pierwszy widget mapy w aplikacji. Wybierz tutaj, jeśli aplikacja ma więcej niż jedną mapę.",
        sites: "Strony",
        siteIndex: "Strona {index}",
        moveUp: "Przesuń w górę",
        moveSiteIndexUp: "Przenieś stronę {index} Początek rozdziału",
        moveDown: "Przesuń w dół",
        moveSiteIndexDown: "Przenieś stronę {index} w dół",
        label: "Etykieta",
        siteName: "Nazwa strony",
        url: "Adres URL",
        remove: "Usuń",
        addSite: "Dodaj stronę"
      })
    }
  }
})
