/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Mapa Base",
        mapWidget: "Widget do mapa",
        carryBasemapToNextMap: "Leve o mapa para o próximo mapa.",
        sendsTheBasemapChosenInEither: "Envia o mapa escolhido em qualquer galeria para o próximo aplicativo. O aplicativo de destino precisa de um interruptor de mapa conectado ao mapa para aplicá-lo.",
        noMapSelectedTheFirstMap: "Nenhum mapa selecionado: o primeiro widget do mapa no aplicativo é usado. Selecione um aqui se o aplicativo tiver mais de um mapa.",
        sites: "Sites",
        siteIndex: "Site {index}",
        moveUp: "Mover para Cima",
        moveSiteIndexUp: "Mova o site {index} Para cima.",
        moveDown: "Mover para baixo",
        moveSiteIndexDown: "Mova o site {index} Para baixo.",
        label: "Rótulo",
        siteName: "Nome do site",
        url: "URL",
        remove: "Remover",
        addSite: "Adicionar site"
      })
    }
  }
})
