/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Mapa Base",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Carregar o mapa de base para o próximo mapa",
        sendsTheBasemapChosenInEither: "Envia o mapa de base escolhido em qualquer galeria de mapas de base para o próximo aplicativo. O aplicativo de destino precisa de um switcher de mapa conectado ao seu mapa para aplicá-lo.",
        noMapSelectedTheFirstMap: "Nenhum mapa selecionado: o primeiro widget do Mapa na aplicação é usado. Selecione um aqui se a aplicação tiver mais de um mapa.",
        sites: "Sites",
        siteIndex: "Local {index}",
        moveUp: "Mover para cima",
        moveSiteIndexUp: "Mover site {index} up",
        moveDown: "Mover para baixo",
        moveSiteIndexDown: "Mover site {index} para baixo",
        label: "Etiqueta",
        siteName: "Nome do sítio",
        url: "URL",
        remove: "Remover",
        addSite: "Adicionar um Site"
      })
    }
  }
})
