/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Hartă fundal",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Carry basemap la harta următoare",
        sendsTheBasemapChosenInEither: "Trimite harta de bază aleasă în oricare galerie de bază la următoarea aplicație. Aplicația de destinație are nevoie de un Switcher de hartă conectat la harta sa pentru a o aplica.",
        noMapSelectedTheFirstMap: "Nicio hartă selectată: prima hartă widget din aplicație este utilizată. Alegeți unul aici dacă aplicația are mai mult de o hartă.",
        sites: "Locuri",
        siteIndex: "Site {index}",
        moveUp: "Deplasare în sus",
        moveSiteIndexUp: "Mută locul {index} sus",
        moveDown: "Deplasare în jos",
        moveSiteIndexDown: "Mută locul {index} jos",
        label: "Etichetă",
        siteName: "Numele locului",
        url: "URL",
        remove: "Eliminare",
        addSite: "Adaugă site"
      })
    }
  }
})
