/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Базовая карта",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Перенос базовой карты на следующую карту",
        sendsTheBasemapChosenInEither: "Отправляет базовую карту, выбранную в любой галерее базовой карты, в следующее приложение. Приложению назначения нужен коммутатор карты, подключенный к его карте, чтобы применить его.",
        noMapSelectedTheFirstMap: "Карта не выбрана: используется первый виджет карты в приложении. Выберите один из них, если приложение имеет более одной карты.",
        sites: "Сайты",
        siteIndex: "Сайт {index}",
        moveUp: "Выше",
        moveSiteIndexUp: "Переместить сайт {index} вверх",
        moveDown: "Ниже",
        moveSiteIndexDown: "Переместить сайт {index} вниз",
        label: "Подпись",
        siteName: "Название сайта",
        url: "URL",
        remove: "Удалить",
        addSite: "Добавить сайт"
      })
    }
  }
})
