/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Podkladová mapa",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Nosiť basemap na nasledujúcu mapu",
        sendsTheBasemapChosenInEither: "Poslať basemap vybraný v oboch basemap galérie do ďalšej aplikácie. Cieľová aplikácia potrebuje Map Switcher pripojený na svoju mapu.",
        noMapSelectedTheFirstMap: "Nevybraná mapa: v aplikácii sa používa prvý widget Mapy. Vyberte jednu, ak má aplikácia viac ako jednu mapu.",
        sites: "Miesta",
        siteIndex: "Miesto {index}",
        moveUp: "Posunúť hore",
        moveSiteIndexUp: "Presunúť stránku {index} Hore",
        moveDown: "Posunúť dolu",
        moveSiteIndexDown: "Presunúť stránku {index} dole",
        label: "Označenie",
        siteName: "Názov lokality",
        url: "URL",
        remove: "Odstrániť",
        addSite: "Pridať stránku"
      })
    }
  }
})
