/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Temeljna karta",
        mapWidget: "Gradnik zemljevida",
        carryBasemapToNextMap: "Prenos osnovne karte na naslednjo karto",
        sendsTheBasemapChosenInEither: "V naslednji aplikaciji pošlje izbrano osnovno karto v galeriji. Ciljna aplikacija za uporabo potrebuje Map Switcher, ki je povezan z zemljevidom.",
        noMapSelectedTheFirstMap: "Ni izbrane karte: uporabljen je prvi gradnik zemljevida v aplikaciji. Tu izberite enega, če ima aplikacija več kot en zemljevid.",
        sites: "Mesta",
        siteIndex: "Kraj {index}",
        moveUp: "Premakni gor",
        moveSiteIndexUp: "Premakni mesto {index} Gor.",
        moveDown: "Premakni dol",
        moveSiteIndexDown: "Premakni mesto {index} Dol",
        label: "Napis",
        siteName: "Ime območja",
        url: "URL",
        remove: "Odstrani",
        addSite: "Dodaj mesto"
      })
    }
  }
})
