/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Baskarta",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Carry Basemap till nästa karta",
        sendsTheBasemapChosenInEither: "Skickar baskartan som valts i antingen basemap galleri till nästa app. Den destination app behöver en karta Switcher ansluten till sin karta för att tillämpa den.",
        noMapSelectedTheFirstMap: "Ingen karta vald: den första kartan widget i appen används. Välj en här om appen har mer än en karta.",
        sites: "Webbplatser",
        siteIndex: "Webbplats {index}",
        moveUp: "Flytta uppåt",
        moveSiteIndexUp: "Flytta plats {index} Upp",
        moveDown: "Flytta nedåt",
        moveSiteIndexDown: "Flytta plats {index} ner",
        label: "Etikett",
        siteName: "Webbplatsnamn",
        url: "URL",
        remove: "Ta bort",
        addSite: "Lägg till webbplats"
      })
    }
  }
})
