/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "แผนที่ฐาน",
        mapWidget: "วิดเจ็ตของแผนที่",
        carryBasemapToNextMap: "ลากฐานแมพไปยังแผนที่ถัดไป",
        sendsTheBasemapChosenInEither: "ส่งบาแมปที่ถูกเลือกในคลังภาพฐานแมปไปยังโปรแกรมถัดไป App ปลายทางต้องการตัวสลับแผนที่ที่เชื่อมต่อกับแผนที่ของมันเพื่อนําไปใช้",
        noMapSelectedTheFirstMap: "ยังไม่มีการเลือกแผนที่: วิดเจ็ตแรกของแผนที่ในโปรแกรม เลือกที่นี่ หากโปรแกรมมีแผนที่มากกว่าหนึ่งตัว",
        sites: "ที่นั่ง",
        siteIndex: "Site {index}",
        moveUp: "เลื่อนขึ้น",
        moveSiteIndexUp: "ย้ายไซต์ {index} ขึ้น",
        moveDown: "เลื่อนลง",
        moveSiteIndexDown: "ย้ายไซต์ {index} ลง",
        label: "ป้ายชื่อ",
        siteName: "ชื่อไซต์",
        url: "ที่อยู่ URL",
        remove: "ลบทิ้ง",
        addSite: "เพิ่มไซต์"
      })
    }
  }
})
