/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Altlık Harita",
        mapWidget: "Map widget",
        carryBasemapToNextMap: "Basemap'ı bir sonraki haritaya taşıyın",
        sendsTheBasemapChosenInEither: "Bazmap galeride bir sonraki uygulama için seçilen üssü gönderin. Hedef uygulama, onu uygulamak için haritasına bağlı bir Map Switcher'e ihtiyaç duyar.",
        noMapSelectedTheFirstMap: "Seçilen harita yok: Uygulamadaki ilk Map widget kullanılır. Uygulamanın birden fazla haritaya sahip olup olmadığını buradan seçin.",
        sites: "Siteler",
        siteIndex: "Site Sitesi {index}",
        moveUp: "Yukarı taşı",
        moveSiteIndexUp: "Move site {index} yukarı yukarı yukarı",
        moveDown: "Aşağı taşı",
        moveSiteIndexDown: "Move site {index} aşağı aşağı aşağı aşağı aşağı",
        label: "Etiket",
        siteName: "Site adı",
        url: "URL URL URL URL",
        remove: "Kaldır",
        addSite: "Add Site Ekle"
      })
    }
  }
})
