/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Базова карта",
        mapWidget: "Карта віджет",
        carryBasemapToNextMap: "Карта каррі на карті",
        sendsTheBasemapChosenInEither: "Надсилання базової карти, обраної в галереї базової карти на наступний додаток. Програма призначення вимагає перемикача карти, підключеного до його карти, щоб застосувати його.",
        noMapSelectedTheFirstMap: "Немає вибраної карти: використовується перший віджет карти в додатку. Виберіть один тут, якщо додаток має більше однієї карти.",
        sites: "Сайти",
        siteIndex: "Веб-сайт {index}",
        moveUp: "Перемістити вгору",
        moveSiteIndexUp: "Веб-сайт {index} вгору",
        moveDown: "Перемістити вниз",
        moveSiteIndexDown: "Веб-сайт {index} вниз",
        label: "Напис",
        siteName: "Назва сайту",
        url: "Контакти",
        remove: "Вилучити",
        addSite: "Додати сайт"
      })
    }
  }
})
