/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "Bản đồ nền",
        mapWidget: "Thiết bị sơ đồ",
        carryBasemapToNextMap: "Đem sơ đồ cơ bản tới bản đồ kế tiếp",
        sendsTheBasemapChosenInEither: "Gửi sơ đồ cơ bản được chọn trong cả hai khung ảnh cơ bản tới ứng dụng tiếp theo. Ứng dụng đích cần một bộ chuyển bản đồ kết nối với bản đồ để áp dụng nó.",
        noMapSelectedTheFirstMap: "Chưa chọn bản đồ: các ô điều khiển sơ đồ đầu tiên trong ứng dụng này được dùng. Ở đây hãy chọn một nếu ứng dụng có nhiều bản đồ.",
        sites: "Nơi ngồi",
        siteIndex: "Nơi Mạng {index}",
        moveUp: "Di chuyển lên trên",
        moveSiteIndexUp: "Chuyển vị trí {index} lên",
        moveDown: "Di chuyển xuống dưới",
        moveSiteIndexDown: "Chuyển vị trí {index} & Xuống",
        label: "Nhãn",
        siteName: "Tên chỗ",
        url: "URL",
        remove: "Gỡ bỏ",
        addSite: "Thêm chỗ ngồi"
      })
    }
  }
})
