/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "底图",
        mapWidget: "地图部件",
        carryBasemapToNextMap: "将基准映射到下一张地图",
        sendsTheBasemapChosenInEither: "将任一碱性映射画廊中选择的碱性映射发送到下一个应用程序 。 目的地应用需要连接到其地图的地图切换器来应用.",
        noMapSelectedTheFirstMap: "没有选择地图: 应用中的第一个地图部件被使用 。 如果应用程序有多个地图, 请在此选择一个 。",
        sites: "站点",
        siteIndex: "站点 {index}",
        moveUp: "上移",
        moveSiteIndexUp: "移动网站 {index} 上来",
        moveDown: "下移",
        moveSiteIndexDown: "移动网站 {index} 下来",
        label: "标注",
        siteName: "站点名称",
        url: "網址",
        remove: "移除",
        addSite: "添加站点"
      })
    }
  }
})
