/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        basemap: "底圖",
        mapWidget: "地圖元件",
        carryBasemapToNextMap: "將底部圖帶到下一張地圖",
        sendsTheBasemapChosenInEither: "將在任一基底圖畫廊中選擇的基底圖傳送至下一個應用程式 。 目的應用程式需要與其地圖連接的地圖切換器來應用它 。",
        noMapSelectedTheFirstMap: "沒有選擇地圖: 使用應用程式中的第一個地圖元件 。 如果應用程式有不止一個地圖, 請在這裡選擇一個 。",
        sites: "站点",
        siteIndex: "站 {index}",
        moveUp: "上移",
        moveSiteIndexUp: "移動網站 {index} 上",
        moveDown: "下移",
        moveSiteIndexDown: "移動網站 {index} 下",
        label: "標籤",
        siteName: "站點名稱",
        url: "網址",
        remove: "移除",
        addSite: "新增站台"
      })
    }
  }
})
