/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "مسح الخرائط",
        switchTo: "ابدلوا...",
        noSitesConfigured: "No sites configured",
        noSitesConfiguredPleaseConfigureMap: "لا توجد مواقع تم تشكيلها يرجى تحديد مواقع الخرائط في مواقع النوافذ.",
        mapSwitcherSelectAMapTo: "مُفتاح الخرائط - إختار خريطة للملاحة -",
        chooseFromSitesCountAvailableMapsSelecting: "الاختيار من {sitesCount} الخرائط المتاحة. اختيار خريطة سينقلك إلى ذلك الموقع ويبقي القاعدة الحالية",
        chooseFromSitesCountAvailableMapsSelecting2: "الاختيار من {sitesCount} الخرائط المتاحة. اختيار خريطة سينقلك إلى ذلك الموقع",
        chooseFromSitesCountAvailableMapSelecting: "الاختيار من {sitesCount} خريطة متاحة اختيار خريطة سينقلك إلى ذلك الموقع ويبقي القاعدة الحالية",
        chooseFromSitesCountAvailableMapSelecting2: "الاختيار من {sitesCount} خريطة متاحة اختيار خريطة سينقلك إلى ذلك الموقع",
        selectMapToView: "خريطة مختارة للنظر",
        selectAMapToNavigateTo: "اختيار خريطة للبحر إلى وجهة نظر مختلفة",
        navigateToLabel: "Navigate to {label}",
        loading: "جارِ التحميل...",
        navigatingToSelectedMapPleaseWait: "نهضت إلى خريطة مختارة انتظر من فضلك",
        skipToMainContent: "Skip to main content",
        selectedMap: "selected map",
        unknownError: "unknown error",
        unserializableError: "unserializable error"
      })
    }
  }
})
