/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Превключвател на карти",
        switchTo: "Превключи на...",
        noSitesConfigured: "Няма конфигурирани сайтове",
        noSitesConfiguredPleaseConfigureMap: "Няма конфигурирани сайтове. Моля, конфигурирайте сайтовете на картата в настройките на джаджата.",
        mapSwitcherSelectAMapTo: "Превключвател на карти - Изберете карта, към която да преминете",
        chooseFromSitesCountAvailableMapsSelecting: "Избор от {sitesCount} наличните карти. Избирането на карта ще ви насочи към това място и ще запази текущата базова карта.",
        chooseFromSitesCountAvailableMapsSelecting2: "Избор от {sitesCount} наличните карти. Изборът на карта ще ви насочи към това място.",
        chooseFromSitesCountAvailableMapSelecting: "Избор от {sitesCount} Налична карта. Избирането на карта ще ви насочи към това място и ще запази текущата базова карта.",
        chooseFromSitesCountAvailableMapSelecting2: "Избор от {sitesCount} Налична карта. Изборът на карта ще ви насочи към това място.",
        selectMapToView: "Избор на карта за преглед",
        selectAMapToNavigateTo: "Изберете карта за навигация към различен изглед",
        navigateToLabel: "Навигация към {label}",
        loading: "Зареждане...",
        navigatingToSelectedMapPleaseWait: "Навигация към избрана карта. Моля те, почакай.",
        skipToMainContent: "Премини към основното съдържание",
        selectedMap: "selected map",
        unknownError: "unknown error",
        unserializableError: "unserializable error"
      })
    }
  }
})
