/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Přepínač mapy",
        switchTo: "Přepnout na...",
        noSitesConfigured: "Žádné stránky nenakonfigurované",
        noSitesConfiguredPleaseConfigureMap: "Žádné stránky nenakonfigurovány. Nastavte prosím mapy v nastavení widget.",
        mapSwitcherSelectAMapTo: "Přepínač mapy - vyberte mapu pro přecházení na",
        chooseFromSitesCountAvailableMapsSelecting: "Vyberte si {sitesCount} dostupné mapy. Volba mapy vás nasměruje na toto místo a uchová aktuální základ.",
        chooseFromSitesCountAvailableMapsSelecting2: "Vyberte si {sitesCount} dostupné mapy. Volba mapy vás navede na toto místo.",
        chooseFromSitesCountAvailableMapSelecting: "Vyberte si {sitesCount} dostupná mapa. Volba mapy vás nasměruje na toto místo a uchová aktuální základ.",
        chooseFromSitesCountAvailableMapSelecting2: "Vyberte si {sitesCount} dostupná mapa. Volba mapy vás navede na toto místo.",
        selectMapToView: "Zvolte mapu pro zobrazení",
        selectAMapToNavigateTo: "Vyberte si mapu pro navigaci do jiného pohledu",
        navigateToLabel: "Přejít na {label}",
        loading: "Nahrávání…",
        navigatingToSelectedMapPleaseWait: "Navigace na vybranou mapu. Prosím, počkejte.",
        skipToMainContent: "Přeskočit na hlavní obsah",
        selectedMap: "vybraná mapa",
        unknownError: "neznámá chyba",
        unserializableError: "neserializovatelná chyba"
      })
    }
  }
})
