/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Διακόπτης χαρτών",
        switchTo: "Αλλαγή σε...",
        noSitesConfigured: "Δεν έχουν ρυθμιστεί περιοχές",
        noSitesConfiguredPleaseConfigureMap: "Δεν έχουν ρυθμιστεί τοποθεσίες. Παρακαλώ ρυθμίστε τις τοποθεσίες χάρτη στις ρυθμίσεις widget.",
        mapSwitcherSelectAMapTo: "Διακόπτης χαρτών - Επιλέξτε έναν χάρτη για πλοήγηση",
        chooseFromSitesCountAvailableMapsSelecting: "Επιλογή από {sitesCount} διαθέσιμους χάρτες. Η επιλογή ενός χάρτη θα σας πλοηγήσει σε αυτή την τοποθεσία και να κρατήσει τον τρέχοντα χάρτη βάσης.",
        chooseFromSitesCountAvailableMapsSelecting2: "Επιλογή από {sitesCount} διαθέσιμους χάρτες. Η επιλογή ενός χάρτη θα σας οδηγήσει σε αυτή την τοποθεσία.",
        chooseFromSitesCountAvailableMapSelecting: "Επιλογή από {sitesCount} διαθέσιμος χάρτης. Η επιλογή ενός χάρτη θα σας πλοηγήσει σε αυτή την τοποθεσία και να κρατήσει τον τρέχοντα χάρτη βάσης.",
        chooseFromSitesCountAvailableMapSelecting2: "Επιλογή από {sitesCount} διαθέσιμος χάρτης. Η επιλογή ενός χάρτη θα σας οδηγήσει σε αυτή την τοποθεσία.",
        selectMapToView: "Επιλογή χάρτη για προβολή",
        selectAMapToNavigateTo: "Επιλέξτε ένα χάρτη για να περιηγηθείτε σε μια διαφορετική προβολή",
        navigateToLabel: "Πλοηγηθείτε σε {label}",
        loading: "Φόρτωση...",
        navigatingToSelectedMapPleaseWait: "Πλοήγηση σε επιλεγμένο χάρτη. Παρακαλώ περιμένετε.",
        skipToMainContent: "Μετάβαση στο κύριο περιεχόμενο"
      })
    }
  }
})
