/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Map Switcher",
        switchTo: "Switch to...",
        noSitesConfigured: "No sites configured",
        noSitesConfiguredPleaseConfigureMap: "No sites configured. Please configure map sites in the widget settings.",
        mapSwitcherSelectAMapTo: "Map Switcher - Select a map to navigate to",
        chooseFromSitesCountAvailableMapsSelecting: "Choose from {sitesCount} available maps. Selecting a map will navigate you to that location and keep the current basemap.",
        chooseFromSitesCountAvailableMapsSelecting2: "Choose from {sitesCount} available maps. Selecting a map will navigate you to that location.",
        chooseFromSitesCountAvailableMapSelecting: "Choose from {sitesCount} available map. Selecting a map will navigate you to that location and keep the current basemap.",
        chooseFromSitesCountAvailableMapSelecting2: "Choose from {sitesCount} available map. Selecting a map will navigate you to that location.",
        selectMapToView: "Select map to view",
        selectAMapToNavigateTo: "Select a map to navigate to a different view",
        navigateToLabel: "Navigate to {label}",
        loading: "Cargando...",
        navigatingToSelectedMapPleaseWait: "Navigating to selected map. Please wait.",
        skipToMainContent: "Skip to main content"
      })
    }
  }
})
