/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Map Switcher",
        switchTo: "Cambia a...",
        noSitesConfigured: "No hay sitios configurados",
        noSitesConfiguredPleaseConfigureMap: "No hay sitios configurados. Por favor configure los sitios de mapa en la configuración del widget.",
        mapSwitcherSelectAMapTo: "Map Switcher - Seleccione un mapa para navegar",
        chooseFromSitesCountAvailableMapsSelecting: "Elija entre {sitesCount} mapas disponibles. Seleccionar un mapa le navegará a esa ubicación y mantendrá el mapa base actual.",
        chooseFromSitesCountAvailableMapsSelecting2: "Elija entre {sitesCount} mapas disponibles. Seleccionar un mapa te navegará a esa ubicación.",
        chooseFromSitesCountAvailableMapSelecting: "Elija entre {sitesCount} mapa disponible. Seleccionar un mapa le navegará a esa ubicación y mantendrá el mapa base actual.",
        chooseFromSitesCountAvailableMapSelecting2: "Elija entre {sitesCount} mapa disponible. Seleccionar un mapa te navegará a esa ubicación.",
        selectMapToView: "Seleccionar mapa para ver",
        selectAMapToNavigateTo: "Seleccione un mapa para navegar a una vista diferente",
        navigateToLabel: "Navigate a {label}",
        loading: "Cargando...",
        navigatingToSelectedMapPleaseWait: "Navegando para el mapa seleccionado. Por favor, espera.",
        skipToMainContent: "Pasar al contenido principal",
        selectedMap: "selected map",
        unknownError: "unknown error",
        unserializableError: "unserializable error"
      })
    }
  }
})
