/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Kaardilüliti",
        switchTo: "Lülitu...",
        noSitesConfigured: "Saite pole seadistatud",
        noSitesConfiguredPleaseConfigureMap: "Saite pole seadistatud. Palun seadista kaardisaite vidina seadistustes.",
        mapSwitcherSelectAMapTo: "Kaardilüliti - vali kaart, kuhu navigeerida",
        chooseFromSitesCountAvailableMapsSelecting: "Vali {sitesCount} olemasolevad kaardid. Kaardi valimine viib teid sellesse asukohta ja hoiab praegust aluskaarti.",
        chooseFromSitesCountAvailableMapsSelecting2: "Vali {sitesCount} olemasolevad kaardid. Kaardi valimine suunab teid sellesse asukohta.",
        chooseFromSitesCountAvailableMapSelecting: "Vali {sitesCount} vaba kaart. Kaardi valimine viib teid sellesse asukohta ja hoiab praegust aluskaarti.",
        chooseFromSitesCountAvailableMapSelecting2: "Vali {sitesCount} vaba kaart. Kaardi valimine suunab teid sellesse asukohta.",
        selectMapToView: "Vaadetava kaardi valimine",
        selectAMapToNavigateTo: "Vali kaart teise vaatesse navigeerimiseks",
        navigateToLabel: "Liikuge {label}",
        loading: "Laadimine...",
        navigatingToSelectedMapPleaseWait: "Liikumine valitud kaardile. Palun oota.",
        skipToMainContent: "Liigu põhisisu juurde",
        selectedMap: "valitud kaart",
        unknownError: "tundmatu viga",
        unserializableError: "seeriaviisiline viga"
      })
    }
  }
})
