/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Karttakytkin",
        switchTo: "Vaihda...",
        noSitesConfigured: "Asetuksia ei ole määritetty",
        noSitesConfiguredPleaseConfigureMap: "Sivustoja ei ole määritetty. Määrittele karttasivustot widget-asetuksissa.",
        mapSwitcherSelectAMapTo: "Karttavaihtaja - Valitse kartta, johon navigoidaan",
        chooseFromSitesCountAvailableMapsSelecting: "Valitse mistä {sitesCount} saatavilla olevat kartat. Kartan valinta navigoi tähän paikkaan ja pitää nykyisen pohjakartta.",
        chooseFromSitesCountAvailableMapsSelecting2: "Valitse mistä {sitesCount} saatavilla olevat kartat. Kartan valinta navigoi tähän paikkaan.",
        chooseFromSitesCountAvailableMapSelecting: "Valitse mistä {sitesCount} käytettävissä oleva kartta. Kartan valinta navigoi tähän paikkaan ja pitää nykyisen pohjakartta.",
        chooseFromSitesCountAvailableMapSelecting2: "Valitse mistä {sitesCount} käytettävissä oleva kartta. Kartan valinta navigoi tähän paikkaan.",
        selectMapToView: "Valitse tarkasteltava kartta",
        selectAMapToNavigateTo: "Valitse toiseen näkymään navigoitava kartta",
        navigateToLabel: "Siirry {label}",
        loading: "Ladataan...",
        navigatingToSelectedMapPleaseWait: "Siirrytään valittuun karttaan. Odota.",
        skipToMainContent: "Siirry pääsisältöön"
      })
    }
  }
})
