/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Commutateur de carte",
        switchTo: "Passez à...",
        noSitesConfigured: "Aucun site configuré",
        noSitesConfiguredPleaseConfigureMap: "Aucun site configuré. Veuillez configurer les sites de carte dans les paramètres du widget.",
        mapSwitcherSelectAMapTo: "Commutateur de carte - Sélectionnez une carte pour naviguer dans",
        chooseFromSitesCountAvailableMapsSelecting: "Choisissez parmi {sitesCount} les cartes disponibles. La sélection d'une carte vous permettra de naviguer à cet endroit et de conserver la carte de base actuelle.",
        chooseFromSitesCountAvailableMapsSelecting2: "Choisissez parmi {sitesCount} les cartes disponibles. Sélectionner une carte vous permettra de naviguer à cet endroit.",
        chooseFromSitesCountAvailableMapSelecting: "Choisissez parmi {sitesCount} carte disponible. La sélection d'une carte vous permettra de naviguer à cet endroit et de conserver la carte de base actuelle.",
        chooseFromSitesCountAvailableMapSelecting2: "Choisissez parmi {sitesCount} carte disponible. Sélectionner une carte vous permettra de naviguer à cet endroit.",
        selectMapToView: "Sélectionnez la carte à afficher",
        selectAMapToNavigateTo: "Sélectionnez une carte pour naviguer vers une vue différente",
        navigateToLabel: "Naviguez vers {label}",
        loading: "Chargement...",
        navigatingToSelectedMapPleaseWait: "Naviguer sur la carte sélectionnée. Attendez.",
        skipToMainContent: "Passer au contenu principal"
      })
    }
  }
})
