/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "מפה Switcher",
        switchTo: "לעבור ל...",
        noSitesConfigured: "אין אתרים שנקבעו",
        noSitesConfiguredPleaseConfigureMap: "שום אתר לא מוגדר. אנא הגדרת אתרי מפות בהגדרות widget.",
        mapSwitcherSelectAMapTo: "Map Switcher - בחר מפה לנווט",
        chooseFromSitesCountAvailableMapsSelecting: "בחר מתוך {sitesCount} מפות זמינות בחירת מפה ת לנווט אותך למיקום זה ולשמור את מפת הבסיס הנוכחית.",
        chooseFromSitesCountAvailableMapsSelecting2: "בחר מתוך {sitesCount} מפות זמינות בחירת מפה ת לנווט אותך למיקום הזה.",
        chooseFromSitesCountAvailableMapSelecting: "בחר מתוך {sitesCount} מפה זמינה בחירת מפה ת לנווט אותך למיקום זה ולשמור את מפת הבסיס הנוכחית.",
        chooseFromSitesCountAvailableMapSelecting2: "בחר מתוך {sitesCount} מפה זמינה בחירת מפה ת לנווט אותך למיקום הזה.",
        selectMapToView: "בחר מפה כדי להציג",
        selectAMapToNavigateTo: "בחר מפה לנווט להשקפה שונה",
        navigateToLabel: "לנווט כדי {label}",
        loading: "טוען...",
        navigatingToSelectedMapPleaseWait: "לנווט במפה שנבחרה. בבקשה חכה.",
        skipToMainContent: "לדלג על התוכן הראשי",
        selectedMap: "selected map",
        unknownError: "unknown error",
        unserializableError: "unserializable error"
      })
    }
  }
})
