/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Térképváltó",
        switchTo: "Váltás...",
        noSitesConfigured: "Nincs beállított oldal",
        noSitesConfiguredPleaseConfigureMap: "Nincs beállított oldal. Kérjük, állítsa be a térkép oldalait a widget beállításokban.",
        mapSwitcherSelectAMapTo: "Térkép switcher - Válasszon ki egy térképet navigálni",
        chooseFromSitesCountAvailableMapsSelecting: "Válasszon {sitesCount} elérhető térképek. A térkép kiválasztása elvezet arra a helyre, és megtartja az aktuális alaplapot.",
        chooseFromSitesCountAvailableMapsSelecting2: "Válasszon {sitesCount} elérhető térképek. A térkép kiválasztása arra a helyre fog irányítani.",
        chooseFromSitesCountAvailableMapSelecting: "Válasszon {sitesCount} elérhető térkép. A térkép kiválasztása elvezet arra a helyre, és megtartja az aktuális alaplapot.",
        chooseFromSitesCountAvailableMapSelecting2: "Válasszon {sitesCount} elérhető térkép. A térkép kiválasztása arra a helyre fog irányítani.",
        selectMapToView: "Válassza ki a megtekintendő térképet",
        selectAMapToNavigateTo: "Válasszon ki egy térképet egy másik nézethez",
        navigateToLabel: "Naiv {label}",
        loading: "Betöltés...",
        navigatingToSelectedMapPleaseWait: "Navigáció a kijelölt térképre. Kérem, várjon.",
        skipToMainContent: "Ugrás a fő tartalomra"
      })
    }
  }
})
