/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Pengalih Peta",
        switchTo: "Ganti ke...",
        noSitesConfigured: "Tidak ada situs yang dikonfigurasi",
        noSitesConfiguredPleaseConfigureMap: "Tidak ada situs yang dikonfigurasi. Silakan konfigurasi situs peta di pengaturan widget.",
        mapSwitcherSelectAMapTo: "Pengalih Peta - Pilih peta untuk menavigasi ke",
        chooseFromSitesCountAvailableMapsSelecting: "Pilih dari {sitesCount} peta yang tersedia. Memilih sebuah peta akan menavigasi Anda ke lokasi itu dan menjaga peta bawah tanah saat ini.",
        chooseFromSitesCountAvailableMapsSelecting2: "Pilih dari {sitesCount} peta yang tersedia. Memilih peta akan menavigasi Anda ke lokasi itu.",
        chooseFromSitesCountAvailableMapSelecting: "Pilih dari {sitesCount} peta yang tersedia. Memilih sebuah peta akan menavigasi Anda ke lokasi itu dan menjaga peta bawah tanah saat ini.",
        chooseFromSitesCountAvailableMapSelecting2: "Pilih dari {sitesCount} peta yang tersedia. Memilih peta akan menavigasi Anda ke lokasi itu.",
        selectMapToView: "Pilih peta yang akan ditampilkan",
        selectAMapToNavigateTo: "Pilih peta untuk menavigasi ke tampilan lain",
        navigateToLabel: "Navigasi ke {label}",
        loading: "Memuat...",
        navigatingToSelectedMapPleaseWait: "Navigasi ke peta terpilih. Tunggu sebentar.",
        skipToMainContent: "Lewati ke isi utama",
        selectedMap: "selected map",
        unknownError: "unknown error",
        unserializableError: "unserializable error"
      })
    }
  }
})
