/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Mappa Switcher",
        switchTo: "Passa a...",
        noSitesConfigured: "Nessun sito configurato",
        noSitesConfiguredPleaseConfigureMap: "Nessun sito configurato. Si prega di configurare i siti di mappa nelle impostazioni del widget.",
        mapSwitcherSelectAMapTo: "Mappa Switcher - Seleziona una mappa per navigare",
        chooseFromSitesCountAvailableMapsSelecting: "Scegli tra {sitesCount} mappe disponibili. La selezione di una mappa ti porterà in quella posizione e manterrà la mappa di base corrente.",
        chooseFromSitesCountAvailableMapsSelecting2: "Scegli tra {sitesCount} mappe disponibili. La selezione di una mappa ti porterà in quella posizione.",
        chooseFromSitesCountAvailableMapSelecting: "Scegli tra {sitesCount} mappa disponibile. La selezione di una mappa ti porterà in quella posizione e manterrà la mappa di base corrente.",
        chooseFromSitesCountAvailableMapSelecting2: "Scegli tra {sitesCount} mappa disponibile. La selezione di una mappa ti porterà in quella posizione.",
        selectMapToView: "Seleziona la mappa per visualizzare",
        selectAMapToNavigateTo: "Seleziona una mappa per navigare in una vista diversa",
        navigateToLabel: "Navigare per {label}",
        loading: "Caricamento in corso...",
        navigatingToSelectedMapPleaseWait: "Navigando alla mappa selezionata. Ti prego, aspetta.",
        skipToMainContent: "Salta al contenuto principale"
      })
    }
  }
})
