/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "地図のスイッチャー",
        switchTo: "スイッチ...",
        noSitesConfigured: "サイト構成なし",
        noSitesConfiguredPleaseConfigureMap: "設定されていないサイト ウィジェットの設定でマップサイトを設定してください。",
        mapSwitcherSelectAMapTo: "地図のスイッチャー - 地図を選択してナビゲーション",
        chooseFromSitesCountAvailableMapsSelecting: "から選ぶ {sitesCount} サイトマップ 地図を選択すると、その場所に移動し、現在のベースマップを保持します。",
        chooseFromSitesCountAvailableMapsSelecting2: "から選ぶ {sitesCount} サイトマップ 地図を選択すると、その場所に移動します。",
        chooseFromSitesCountAvailableMapSelecting: "から選ぶ {sitesCount} サイトマップ 地図を選択すると、その場所に移動し、現在のベースマップを保持します。",
        chooseFromSitesCountAvailableMapSelecting2: "から選ぶ {sitesCount} サイトマップ 地図を選択すると、その場所に移動します。",
        selectMapToView: "地図を選択",
        selectAMapToNavigateTo: "異なるビューに移動するためのマップを選択します",
        navigateToLabel: "ナビゲートへ {label}",
        loading: "読み込んでいます...",
        navigatingToSelectedMapPleaseWait: "選択したマップに移動します。 お問い合わせ",
        skipToMainContent: "メインコンテンツへスキップ",
        selectedMap: "選択したマップ",
        unknownError: "未知のエラー",
        unserializableError: "unserializable エラー"
      })
    }
  }
})
