/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Žemėlapio perjungiklis",
        switchTo: "Persijungti į...",
        noSitesConfigured: "Nenurodytos svetainės",
        noSitesConfiguredPleaseConfigureMap: "Nėra sukonfigūruotų svetainių. @ info: whatsthis",
        mapSwitcherSelectAMapTo: "Žemėlapio perjungiklis - Pasirinkite naršyti žemėlapį",
        chooseFromSitesCountAvailableMapsSelecting: "Pasirinkite {sitesCount} turimus žemėlapius. Pasirinkus žemėlapį bus naršyti toje vietoje ir išlaikyti esamą basemap.",
        chooseFromSitesCountAvailableMapsSelecting2: "Pasirinkite {sitesCount} turimus žemėlapius. Pasirinkus žemėlapį nukeliausite į tą vietą.",
        chooseFromSitesCountAvailableMapSelecting: "Pasirinkite {sitesCount} prieinamas žemėlapis. Pasirinkus žemėlapį bus naršyti toje vietoje ir išlaikyti esamą basemap.",
        chooseFromSitesCountAvailableMapSelecting2: "Pasirinkite {sitesCount} prieinamas žemėlapis. Pasirinkus žemėlapį nukeliausite į tą vietą.",
        selectMapToView: "Pažymėti rodomą žemėlapį",
        selectAMapToNavigateTo: "Pasirinkite žemėlapį naršymui į kitą rodinį",
        navigateToLabel: "Eiti į {label}",
        loading: "Įkeliama...",
        navigatingToSelectedMapPleaseWait: "Navigacija į pasirinktą žemėlapį. Palaukite.",
        skipToMainContent: "Praleisti į pagrindinį turinį",
        selectedMap: "selected map",
        unknownError: "unknown error",
        unserializableError: "unserializable error"
      })
    }
  }
})
