/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Kartes pārslēdzējs",
        switchTo: "Pārslēgties uz...",
        noSitesConfigured: "Nav konfigurēta neviena vietne",
        noSitesConfiguredPleaseConfigureMap: "Nav konfigurēta neviena vietne. Lūdzu konfigurējiet kartes vietnes logdaļu iestatījumos.",
        mapSwitcherSelectAMapTo: "Kartes pārslēdzējs - Izvēlieties karti, uz kuru doties",
        chooseFromSitesCountAvailableMapsSelecting: "Izvēlieties {sitesCount} pieejamās kartes. Izvēloties karti, jūs pārcelsiet uz šo vietu un saglabāsiet pašreizējo bāzes karti.",
        chooseFromSitesCountAvailableMapsSelecting2: "Izvēlieties {sitesCount} pieejamās kartes. Izvēloties karti, jūs pārvietos uz šo vietu.",
        chooseFromSitesCountAvailableMapSelecting: "Izvēlieties {sitesCount} pieejamā karte. Izvēloties karti, jūs pārcelsiet uz šo vietu un saglabāsiet pašreizējo bāzes karti.",
        chooseFromSitesCountAvailableMapSelecting2: "Izvēlieties {sitesCount} pieejamā karte. Izvēloties karti, jūs pārvietos uz šo vietu.",
        selectMapToView: "Izvēlieties apskatāmo karti",
        selectAMapToNavigateTo: "Izvēlieties karti, ko pārvietot uz citu skatu",
        navigateToLabel: "Pārvietoties uz {label}",
        loading: "Ielādē...",
        navigatingToSelectedMapPleaseWait: "Virzīties uz izvēlēto karti. Lūdzu, uzgaidiet.",
        skipToMainContent: "Pāriet uz galveno saturu"
      })
    }
  }
})
