/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Kaartenwisselaar",
        switchTo: "Overschakelen naar...",
        noSitesConfigured: "Geen sites ingesteld",
        noSitesConfiguredPleaseConfigureMap: "Geen sites geconfigureerd. Configureren van kaart sites in de widget-instellingen.",
        mapSwitcherSelectAMapTo: "Kaartenwisselaar - Selecteer een kaart om naar te navigeren",
        chooseFromSitesCountAvailableMapsSelecting: "Kies uit {sitesCount} beschikbare kaarten. Een kaart selecteren zal u naar die locatie navigeren en de huidige basismap behouden.",
        chooseFromSitesCountAvailableMapsSelecting2: "Kies uit {sitesCount} beschikbare kaarten. Een kaart selecteren zal u naar die locatie navigeren.",
        chooseFromSitesCountAvailableMapSelecting: "Kies uit {sitesCount} beschikbare kaart. Een kaart selecteren zal u naar die locatie navigeren en de huidige basismap behouden.",
        chooseFromSitesCountAvailableMapSelecting2: "Kies uit {sitesCount} beschikbare kaart. Een kaart selecteren zal u naar die locatie navigeren.",
        selectMapToView: "Selecteer de kaart om te bekijken",
        selectAMapToNavigateTo: "Selecteer een kaart om naar een andere weergave te navigeren",
        navigateToLabel: "Navigeren naar {label}",
        loading: "Bezig met laden...",
        navigatingToSelectedMapPleaseWait: "Navigeren naar geselecteerde kaart. Wacht even.",
        skipToMainContent: "Overslaan en naar de inhoud gaan"
      })
    }
  }
})
