/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Kartbryter",
        switchTo: "Bytt til...",
        noSitesConfigured: "Ingen nettsteder satt opp",
        noSitesConfiguredPleaseConfigureMap: "Ingen nettsteder konfigurert. Vennligst konfigurer kartsider i elementinnstillingene.",
        mapSwitcherSelectAMapTo: "Kartbryter - Velg et kart for å navigere til",
        chooseFromSitesCountAvailableMapsSelecting: "Velg mellom {sitesCount} tilgjengelige kart. Å velge et kart vil navigere deg til den plasseringen og holde gjeldende basiskart.",
        chooseFromSitesCountAvailableMapsSelecting2: "Velg mellom {sitesCount} tilgjengelige kart. Å velge et kart vil navigere deg til det stedet.",
        chooseFromSitesCountAvailableMapSelecting: "Velg mellom {sitesCount} Tilgjengelig kart. Å velge et kart vil navigere deg til den plasseringen og holde gjeldende basiskart.",
        chooseFromSitesCountAvailableMapSelecting2: "Velg mellom {sitesCount} Tilgjengelig kart. Å velge et kart vil navigere deg til det stedet.",
        selectMapToView: "Velg kart som skal vises",
        selectAMapToNavigateTo: "Velg et kart for å navigere til en annen visning",
        navigateToLabel: "Gå til {label}",
        loading: "Laster inn...",
        navigatingToSelectedMapPleaseWait: "Navigasjon til valgt kart. Vent.",
        skipToMainContent: "Hopp til hovedinnhold",
        selectedMap: "valgt kart",
        unknownError: "ukjent feil",
        unserializableError: "uiserbar feil"
      })
    }
  }
})
