/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Przełącznik map",
        switchTo: "Przełącz na...",
        noSitesConfigured: "Brak skonfigurowanych stron",
        noSitesConfiguredPleaseConfigureMap: "Brak skonfigurowanych stron. Proszę skonfigurować strony mapy w ustawieniach widget.",
        mapSwitcherSelectAMapTo: "Map Switcher - Wybierz mapę do nawigacji",
        chooseFromSitesCountAvailableMapsSelecting: "Wybierz {sitesCount} dostępne mapy. Wybierając mapę, przejdziesz do tego miejsca i zachowasz obecną bazę danych.",
        chooseFromSitesCountAvailableMapsSelecting2: "Wybierz {sitesCount} dostępne mapy. Wybór mapy poprowadzi cię do tego miejsca.",
        chooseFromSitesCountAvailableMapSelecting: "Wybierz {sitesCount} dostępna mapa. Wybierając mapę, przejdziesz do tego miejsca i zachowasz obecną bazę danych.",
        chooseFromSitesCountAvailableMapSelecting2: "Wybierz {sitesCount} dostępna mapa. Wybór mapy poprowadzi cię do tego miejsca.",
        selectMapToView: "Wybierz mapę do wyświetlenia",
        selectAMapToNavigateTo: "Wybierz mapę do nawigacji do innego widoku",
        navigateToLabel: "Przejdź do {label}",
        loading: "Wczytywanie...",
        navigatingToSelectedMapPleaseWait: "Nawigacja do wybranej mapy. Proszę poczekać.",
        skipToMainContent: "Przejdź do głównej treści",
        selectedMap: "wybrana mapa",
        unknownError: "nieznany błąd",
        unserializableError: "błąd niezserializowalny"
      })
    }
  }
})
