/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Comutador de mapas",
        switchTo: "Mude para...",
        noSitesConfigured: "Nenhum site configurado",
        noSitesConfiguredPleaseConfigureMap: "Nenhum site configurado. Por favor, configure os sites de mapas nas configurações do widget.",
        mapSwitcherSelectAMapTo: "Seleciona um mapa para onde navegar",
        chooseFromSitesCountAvailableMapsSelecting: "Escolha entre {sitesCount} mapas disponíveis. Se selecionar um mapa irá navegar até esse local e manterá o mapa de base atual.",
        chooseFromSitesCountAvailableMapsSelecting2: "Escolha entre {sitesCount} mapas disponíveis. Selecionar um mapa irá navegar até esse local.",
        chooseFromSitesCountAvailableMapSelecting: "Escolha entre {sitesCount} mapa disponível. Se selecionar um mapa irá navegar até esse local e manterá o mapa de base atual.",
        chooseFromSitesCountAvailableMapSelecting2: "Escolha entre {sitesCount} mapa disponível. Selecionar um mapa irá navegar até esse local.",
        selectMapToView: "Selecione o mapa para ver",
        selectAMapToNavigateTo: "Selecione um mapa para navegar para uma visão diferente",
        navigateToLabel: "Navegar para {label}",
        loading: "Carregando...",
        navigatingToSelectedMapPleaseWait: "Navegando para o mapa selecionado. Por favor, espere.",
        skipToMainContent: "Ir para o conteúdo principal",
        selectedMap: "mapa selecionado",
        unknownError: "Erro desconhecido",
        unserializableError: "Erro inserializável"
      })
    }
  }
})
