/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Comutador de mapas",
        switchTo: "Mudar para...",
        noSitesConfigured: "Nenhum site configurado",
        noSitesConfiguredPleaseConfigureMap: "Nenhum site configurado. Por favor, configure os sites do mapa nas configurações do widget.",
        mapSwitcherSelectAMapTo: "Comutador de mapas - Selecione um mapa para onde navegar",
        chooseFromSitesCountAvailableMapsSelecting: "Escolher entre {sitesCount} mapas disponíveis. Selecionar um mapa irá navegar até esse local e manter o mapa de base atual.",
        chooseFromSitesCountAvailableMapsSelecting2: "Escolher entre {sitesCount} mapas disponíveis. Selecionar um mapa irá navegar até esse local.",
        chooseFromSitesCountAvailableMapSelecting: "Escolher entre {sitesCount} mapa disponível. Selecionar um mapa irá navegar até esse local e manter o mapa de base atual.",
        chooseFromSitesCountAvailableMapSelecting2: "Escolher entre {sitesCount} mapa disponível. Selecionar um mapa irá navegar até esse local.",
        selectMapToView: "Seleccione o mapa a ver",
        selectAMapToNavigateTo: "Selecione um mapa para navegar para uma visão diferente",
        navigateToLabel: "Navegar para {label}",
        loading: "A carregar...",
        navigatingToSelectedMapPleaseWait: "Navegando para o mapa selecionado. Por favor, espere.",
        skipToMainContent: "Saltar para o conteúdo principal",
        selectedMap: "mapa selecionado",
        unknownError: "erro desconhecido",
        unserializableError: "erro inserializável"
      })
    }
  }
})
