/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Comutator hartă",
        switchTo: "Comută pe...",
        noSitesConfigured: "Niciun site configurat",
        noSitesConfiguredPleaseConfigureMap: "Niciun site configurat. Configurează site-urile hărților în setările widget.",
        mapSwitcherSelectAMapTo: "Switcher hartă - Selectați o hartă la care să navigați",
        chooseFromSitesCountAvailableMapsSelecting: "Alege din {sitesCount} hărți disponibile. Selectați o hartă vă va naviga la acea locație și să păstreze harta de bază curentă.",
        chooseFromSitesCountAvailableMapsSelecting2: "Alege din {sitesCount} hărți disponibile. Alegeți o hartă vă va naviga la acea locație.",
        chooseFromSitesCountAvailableMapSelecting: "Alege din {sitesCount} harta disponibilă. Selectați o hartă vă va naviga la acea locație și să păstreze harta de bază curentă.",
        chooseFromSitesCountAvailableMapSelecting2: "Alege din {sitesCount} harta disponibilă. Alegeți o hartă vă va naviga la acea locație.",
        selectMapToView: "Alegeți harta de văzut",
        selectAMapToNavigateTo: "Alegeți o hartă pentru a naviga la o vizualizare diferită",
        navigateToLabel: "Navighează la {label}",
        loading: "Se încarcă...",
        navigatingToSelectedMapPleaseWait: "Navigare către harta selectată. Te rog aşteaptă.",
        skipToMainContent: "Sari la conținutul principal"
      })
    }
  }
})
