/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Переключатель карт",
        switchTo: "Переключитесь на...",
        noSitesConfigured: "Сайты не настроены",
        noSitesConfiguredPleaseConfigureMap: "Сайты не настроены. Пожалуйста, настройте сайты карты в настройках виджета.",
        mapSwitcherSelectAMapTo: "Map Switcher - Выберите карту для навигации",
        chooseFromSitesCountAvailableMapsSelecting: "Выбрать из {sitesCount} Доступные карты. Выбор карты приведет вас к этому месту и сохранит текущую базовую карту.",
        chooseFromSitesCountAvailableMapsSelecting2: "Выбрать из {sitesCount} Доступные карты. Выбор карты приведет вас к этому месту.",
        chooseFromSitesCountAvailableMapSelecting: "Выбрать из {sitesCount} Доступная карта. Выбор карты приведет вас к этому месту и сохранит текущую базовую карту.",
        chooseFromSitesCountAvailableMapSelecting2: "Выбрать из {sitesCount} Доступная карта. Выбор карты приведет вас к этому месту.",
        selectMapToView: "Выберите карту для просмотра",
        selectAMapToNavigateTo: "Выберите карту, чтобы перейти к другому виду",
        navigateToLabel: "Навигация для {label}",
        loading: "Загрузка...",
        navigatingToSelectedMapPleaseWait: "Переход на выбранную карту. Пожалуйста, подождите.",
        skipToMainContent: "Пропустить основной контент",
        selectedMap: "выбранная карта",
        unknownError: "Неизвестная ошибка",
        unserializableError: "несериализируемая ошибка"
      })
    }
  }
})
