/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Prepínač mapy",
        switchTo: "Prepnúť na...",
        noSitesConfigured: "Žiadne konfigurované stránky",
        noSitesConfiguredPleaseConfigureMap: "Žiadne stránky konfigurované. Prosím, konfigurujte mapové stránky v nastaveniach widgetu.",
        mapSwitcherSelectAMapTo: "Mapový switcher - Vyberte mapu pre navigáciu",
        chooseFromSitesCountAvailableMapsSelecting: "Vyberte z {sitesCount} dostupné mapy. Výber mapy vás naviguje na toto miesto a zachová aktuálnu mapu.",
        chooseFromSitesCountAvailableMapsSelecting2: "Vyberte z {sitesCount} dostupné mapy. Výberom mapy sa dostanete na toto miesto.",
        chooseFromSitesCountAvailableMapSelecting: "Vyberte z {sitesCount} dostupná mapa. Výber mapy vás naviguje na toto miesto a zachová aktuálnu mapu.",
        chooseFromSitesCountAvailableMapSelecting2: "Vyberte z {sitesCount} dostupná mapa. Výberom mapy sa dostanete na toto miesto.",
        selectMapToView: "Vyberte mapu pre zobrazenie",
        selectAMapToNavigateTo: "Vyberte mapu pre prechod na iný pohľad",
        navigateToLabel: "Navigovať do {label}",
        loading: "Načítava sa...",
        navigatingToSelectedMapPleaseWait: "Navigácia na vybranú mapu. Prosím, počkajte.",
        skipToMainContent: "Preskočiť na hlavný obsah"
      })
    }
  }
})
