/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Preklopnik zemljevidov",
        switchTo: "Preklopi na...",
        noSitesConfigured: "Ni nastavljenih mest",
        noSitesConfiguredPleaseConfigureMap: "Ni nastavljenih mest. Nastavite mesta zemljevida v nastavitvah gradnikov.",
        mapSwitcherSelectAMapTo: "Preklopnik zemljevidov - Izberite zemljevid za navigacijo",
        chooseFromSitesCountAvailableMapsSelecting: "Izberite med {sitesCount} razpoložljive zemljevide. Izbira zemljevida vas bo usmerila na to lokacijo in ohranila trenutno osnovno karto.",
        chooseFromSitesCountAvailableMapsSelecting2: "Izberite med {sitesCount} razpoložljive zemljevide. Izbira zemljevida vas bo napotila na to lokacijo.",
        chooseFromSitesCountAvailableMapSelecting: "Izberite med {sitesCount} razpoložljiv zemljevid. Izbira zemljevida vas bo usmerila na to lokacijo in ohranila trenutno osnovno karto.",
        chooseFromSitesCountAvailableMapSelecting2: "Izberite med {sitesCount} razpoložljiv zemljevid. Izbira zemljevida vas bo napotila na to lokacijo.",
        selectMapToView: "Izberite zemljevid za ogled",
        selectAMapToNavigateTo: "Izberite zemljevid za navigacijo v drug prikaz",
        navigateToLabel: "Navigacija za {label}",
        loading: "Nalaganje...",
        navigatingToSelectedMapPleaseWait: "Navigacija na izbrano karto. Prosim, počakajte.",
        skipToMainContent: "Preskoči na glavno vsebino",
        selectedMap: "izbrana karta",
        unknownError: "neznana napaka",
        unserializableError: "Neizvedljiva napaka"
      })
    }
  }
})
