/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Karta Switcher",
        switchTo: "Växla till...",
        noSitesConfigured: "Inga webbplatser konfigurerade",
        noSitesConfiguredPleaseConfigureMap: "Inga webbplatser konfigurerade. Konfigurera kartplatser i widgetinställningarna.",
        mapSwitcherSelectAMapTo: "Karta Switcher - Välj en karta för att navigera för att",
        chooseFromSitesCountAvailableMapsSelecting: "Välj mellan {sitesCount} tillgängliga kartor. Välja en karta kommer att navigera dig till den platsen och hålla den aktuella baskartan.",
        chooseFromSitesCountAvailableMapsSelecting2: "Välj mellan {sitesCount} tillgängliga kartor. Välja en karta kommer att navigera dig till den platsen.",
        chooseFromSitesCountAvailableMapSelecting: "Välj mellan {sitesCount} tillgänglig karta. Välja en karta kommer att navigera dig till den platsen och hålla den aktuella baskartan.",
        chooseFromSitesCountAvailableMapSelecting2: "Välj mellan {sitesCount} tillgänglig karta. Välja en karta kommer att navigera dig till den platsen.",
        selectMapToView: "Välj karta för att visa",
        selectAMapToNavigateTo: "Välj en karta för att navigera till en annan vy",
        navigateToLabel: "Navigera till {label}",
        loading: "Läser in...",
        navigatingToSelectedMapPleaseWait: "Navigera till vald karta. Vänta.",
        skipToMainContent: "Hoppa till huvudinnehåll"
      })
    }
  }
})
