/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "ตัวสลับผังแผนที่",
        switchTo: "สลับไปยัง...",
        noSitesConfigured: "ยังไม่มีการกําหนดเว็บไซต์ใด ๆ",
        noSitesConfiguredPleaseConfigureMap: "ยังไม่มีการปรับแต่งเว็บไซต์ โปรดทําการปรับแต่งไซต์แผนที่ในการตั้งค่าวิดเจ็ต",
        mapSwitcherSelectAMapTo: "โปรแกรมสลับแผนที่ - เลือกแผนที่ที่จะใช้นําทางไปยัง",
        chooseFromSitesCountAvailableMapsSelecting: "เลือกจาก {sitesCount} มีแผนที่อยู่ การเลือกแผนที่จะนําทางคุณไปยังสถานที่นั้น และเก็บฐานแมปปัจจุบันไว้",
        chooseFromSitesCountAvailableMapsSelecting2: "เลือกจาก {sitesCount} มีแผนที่อยู่ การเลือกแผนที่จะนําทางคุณไปยังสถานที่นั้น",
        chooseFromSitesCountAvailableMapSelecting: "เลือกจาก {sitesCount} มีแผนที่อยู่ การเลือกแผนที่จะนําทางคุณไปยังสถานที่นั้น และเก็บฐานแมปปัจจุบันไว้",
        chooseFromSitesCountAvailableMapSelecting2: "เลือกจาก {sitesCount} มีแผนที่อยู่ การเลือกแผนที่จะนําทางคุณไปยังสถานที่นั้น",
        selectMapToView: "เลือกแผนที่ที่จะแสดง",
        selectAMapToNavigateTo: "เลือกแผนที่ที่จะนําทางไปยังมุมมองอื่น",
        navigateToLabel: "นํามายัง {label}",
        loading: "กำลังโหลด...",
        navigatingToSelectedMapPleaseWait: "บินไปยังแผนที่ที่เลือก โปรดรอ",
        skipToMainContent: "ข้ามไปยังเนื้อหาหลัก",
        selectedMap: "selected map",
        unknownError: "unknown error",
        unserializableError: "unserializable error"
      })
    }
  }
})
