/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Map Switcher",
        switchTo: "Switch to...",
        noSitesConfigured: "Hiçbir site yapılandırılmış",
        noSitesConfiguredPleaseConfigureMap: "Hiçbir site yapılandırılmadı. Please configure map sites in the widget settings.",
        mapSwitcherSelectAMapTo: "Map Switcher - gezinmek için bir harita seçin",
        chooseFromSitesCountAvailableMapsSelecting: "Select from Select from {sitesCount} Mevcut haritalar. Bir haritayı seçmek sizi o yere götürecek ve mevcut bazmap tutacaktır.",
        chooseFromSitesCountAvailableMapsSelecting2: "Select from Select from {sitesCount} Mevcut haritalar. Bir harita seçmek sizi bu yere götürecek.",
        chooseFromSitesCountAvailableMapSelecting: "Select from Select from {sitesCount} Mevcut harita. Bir haritayı seçmek sizi o yere götürecek ve mevcut bazmap tutacaktır.",
        chooseFromSitesCountAvailableMapSelecting2: "Select from Select from {sitesCount} Mevcut harita. Bir harita seçmek sizi bu yere götürecek.",
        selectMapToView: "Görmek için harita seçin",
        selectAMapToNavigateTo: "Farklı bir görüşe gitmek için bir harita seçin",
        navigateToLabel: "Navigate to {label}",
        loading: "Yükleniyor...",
        navigatingToSelectedMapPleaseWait: "Seçilmiş haritaya geçiş. Lütfen bekleyin.",
        skipToMainContent: "Skip to main content",
        selectedMap: "Seçilen harita",
        unknownError: "Bilinmeyen hata",
        unserializableError: "Başarısız olmayan hata"
      })
    }
  }
})
