/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Карта Switcher",
        switchTo: "Перемикач...",
        noSitesConfigured: "Немає сайтів, налаштованих",
        noSitesConfiguredPleaseConfigureMap: "Немає сайтів, налаштованих. Будь ласка, налаштуйте сайти на карті в налаштуваннях віджету.",
        mapSwitcherSelectAMapTo: "Карта Switcher - Виберіть карту для навігації",
        chooseFromSitesCountAvailableMapsSelecting: "Виберіть {sitesCount} доступні карти. Вибір карти буде навігувати вас до цього місця розташування і зберігати поточний базовий карти.",
        chooseFromSitesCountAvailableMapsSelecting2: "Виберіть {sitesCount} доступні карти. Вибір карти буде навігати вас на це місце.",
        chooseFromSitesCountAvailableMapSelecting: "Виберіть {sitesCount} доступна карта. Вибір карти буде навігувати вас до цього місця розташування і зберігати поточний базовий карти.",
        chooseFromSitesCountAvailableMapSelecting2: "Виберіть {sitesCount} доступна карта. Вибір карти буде навігати вас на це місце.",
        selectMapToView: "Виберіть карту для перегляду",
        selectAMapToNavigateTo: "Виберіть карту для навігації в інший вид",
        navigateToLabel: "Навігація {label}",
        loading: "Виконується завантаження...",
        navigatingToSelectedMapPleaseWait: "Навігація до вибраної карти. Будь ласка, почекайте.",
        skipToMainContent: "Головна"
      })
    }
  }
})
