/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "Trình đổi bản đồ",
        switchTo: "Chuyển sang...",
        noSitesConfigured: "Chưa cấu hình nơi Mạng",
        noSitesConfiguredPleaseConfigureMap: "Chưa cấu hình nơi Mạng. Hãy cấu hình sơ đồ trong thiết lập ô điều khiển.",
        mapSwitcherSelectAMapTo: "Trình đổi bản đồ - Chọn bản đồ cần định hướng tới",
        chooseFromSitesCountAvailableMapsSelecting: "Chọn từ {sitesCount} Bản đồ có sẵn. Chọn một bản đồ sẽ định hướng bạn đến vị trí đó và giữ sơ đồ cơ sở hiện thời.",
        chooseFromSitesCountAvailableMapsSelecting2: "Chọn từ {sitesCount} Bản đồ có sẵn. Chọn một bản đồ sẽ định hướng bạn đến địa điểm đó.",
        chooseFromSitesCountAvailableMapSelecting: "Chọn từ {sitesCount} có sẵn bản đồ. Chọn một bản đồ sẽ định hướng bạn đến vị trí đó và giữ sơ đồ cơ sở hiện thời.",
        chooseFromSitesCountAvailableMapSelecting2: "Chọn từ {sitesCount} có sẵn bản đồ. Chọn một bản đồ sẽ định hướng bạn đến địa điểm đó.",
        selectMapToView: "Chọn bản đồ cần xem",
        selectAMapToNavigateTo: "Chọn một bản đồ để di chuyển tới một ô xem khác",
        navigateToLabel: "Chuyển tới {label}",
        loading: "Đang tải...",
        navigatingToSelectedMapPleaseWait: "Chuyển sang bản đồ đã chọn. Đợi đã.",
        skipToMainContent: "Bỏ qua nội dung chính"
      })
    }
  }
})
