/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        _widgetLabel: "地圖切換器",
        switchTo: "切換到...",
        noSitesConfigured: "沒有設定站台",
        noSitesConfiguredPleaseConfigureMap: "未設定網站 。 請在元件設定中設定地圖站點 。",
        mapSwitcherSelectAMapTo: "地圖切換器 - 選擇要導航的地圖",
        chooseFromSitesCountAvailableMapsSelecting: "選擇從 {sitesCount} 可用的地圖 。 選擇地圖會導引您到那個位置, 並保留目前的基底圖 。",
        chooseFromSitesCountAvailableMapsSelecting2: "選擇從 {sitesCount} 可用的地圖 。 選擇地圖會導引您到那個位置 。",
        chooseFromSitesCountAvailableMapSelecting: "選擇從 {sitesCount} 可用的地圖 。 選擇地圖會導引您到那個位置, 並保留目前的基底圖 。",
        chooseFromSitesCountAvailableMapSelecting2: "選擇從 {sitesCount} 可用的地圖 。 選擇地圖會導引您到那個位置 。",
        selectMapToView: "選擇要查看的地圖",
        selectAMapToNavigateTo: "選擇通向不同檢視的地圖",
        navigateToLabel: "導航到 {label}",
        loading: "正在載入...",
        navigatingToSelectedMapPleaseWait: "導引到選取的地圖 。 等等",
        skipToMainContent: "跳到主內容",
        selectedMap: "選取的地圖",
        unknownError: "未知的錯誤",
        unserializableError: "不串連的錯誤"
      })
    }
  }
})
